"""Pretraining task heads for the foundation model.

Three heads operate on the encoder output (B, K, d_model):

1. MTMHead (Masked Token Modeling):
   - Reconstructs original token features from masked positions
   - Target: edge_feat + pair_feat (domain-agnostic features)
   - Uses EMA encoder for stable targets (BYOL-style)

2. NTPHead (Next Time Prediction):
   - Predicts time encoding of the next interaction for the query node
   - Pool → MLP → time encoding vector
   - Loss: L2 between predicted and actual time encoding

3. LPHead (Link Prediction):
   - Pool encoded sequence → node vector
   - Dot product similarity → BCE loss
   - Standard link prediction objective
"""

from __future__ import annotations

import copy
import math
from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor


class MTMHead(nn.Module):
    """Masked Token Modeling decoder.

    Reconstructs original token features from encoded representations at
    masked positions. Target features are edge_feat + pair_feat (the
    domain-agnostic components of the input token).

    The reconstruction target is generated by an EMA (exponential moving
    average) encoder to prevent representation collapse (BYOL-style).

    Args:
        d_model: encoder output dimension
        d_target: dimension of reconstruction target
            (d_edge + d_pair, e.g. 172 + 2 = 174)
        d_hidden: decoder hidden dimension (default: d_model)
        n_layers: number of decoder layers (default: 2)
    """

    def __init__(
        self,
        d_model: int,
        d_target: int,
        d_hidden: Optional[int] = None,
        n_layers: int = 2,
    ):
        super().__init__()
        d_hidden = d_hidden or d_model

        layers = []
        d_in = d_model
        for i in range(n_layers - 1):
            layers.extend([
                nn.Linear(d_in, d_hidden),
                nn.GELU(),
                nn.LayerNorm(d_hidden),
            ])
            d_in = d_hidden
        layers.append(nn.Linear(d_in, d_target))
        self.decoder = nn.Sequential(*layers)

    def forward(self, h_masked: Tensor) -> Tensor:
        """Reconstruct features from encoded (masked) tokens.

        Args:
            h_masked: (B, K, d_model) encoder output at masked positions

        Returns:
            (B, K, d_target) reconstructed features
        """
        return self.decoder(h_masked)


class EMAEncoder(nn.Module):
    """Exponential Moving Average encoder for stable MTM targets.

    Maintains a slowly-updating copy of the online encoder. The EMA
    encoder generates reconstruction targets that are stable across
    training steps, preventing representation collapse.

    Usage:
        ema = EMAEncoder(online_encoder, momentum=0.999)
        # During training:
        ema.update(online_encoder)
        target = ema.encoder(input)
    """

    def __init__(self, online_encoder: nn.Module, momentum: float = 0.999):
        super().__init__()
        self.momentum = momentum
        self.encoder = copy.deepcopy(online_encoder)
        # Freeze EMA encoder parameters
        for p in self.encoder.parameters():
            p.requires_grad_(False)

    @torch.no_grad()
    def update(self, online_encoder: nn.Module):
        """Update EMA parameters toward online encoder."""
        for ema_p, online_p in zip(
            self.encoder.parameters(), online_encoder.parameters()
        ):
            ema_p.data.mul_(self.momentum).add_(
                online_p.data, alpha=1.0 - self.momentum
            )

    def forward(self, x: Tensor) -> Tensor:
        return self.encoder(x)


class NTPHead(nn.Module):
    """Next Time Prediction head.

    Predicts the time encoding of the next interaction for a node,
    given its encoded neighbor sequence.

    Architecture: Pool (mean of valid positions) → MLP → time encoding vector

    Args:
        d_model: encoder output dimension
        d_time: time encoding dimension (must match TrainableSinusoidalTimeEncoding)
        d_hidden: MLP hidden dimension (default: d_model // 2)
    """

    def __init__(
        self,
        d_model: int,
        d_time: int,
        d_hidden: Optional[int] = None,
    ):
        super().__init__()
        d_hidden = d_hidden or d_model // 2
        self.pool_norm = nn.LayerNorm(d_model)
        self.mlp = nn.Sequential(
            nn.Linear(d_model, d_hidden),
            nn.GELU(),
            nn.Linear(d_hidden, d_time),
        )

    def forward(self, h: Tensor, mask: Tensor) -> Tensor:
        """Predict next-event time encoding.

        Args:
            h: (B, K, d_model) encoder output
            mask: (B, K) bool, valid positions

        Returns:
            (B, d_time) predicted time encoding vector
        """
        # Mean pool over valid positions
        mask_f = mask.unsqueeze(-1).float()  # (B, K, 1)
        counts = mask_f.sum(dim=1).clamp(min=1)  # (B, 1)
        pooled = (h * mask_f).sum(dim=1) / counts  # (B, d_model)
        pooled = self.pool_norm(pooled)
        return self.mlp(pooled)  # (B, d_time)


class LPHead(nn.Module):
    """Link Prediction head.

    Pools the encoded sequence into a node vector, then computes
    dot-product similarity for link prediction.

    Args:
        d_model: encoder output dimension
    """

    def __init__(self, d_model: int):
        super().__init__()
        self.pool_norm = nn.LayerNorm(d_model)

    def pool(self, h: Tensor, mask: Tensor) -> Tensor:
        """Pool encoded sequence into node vector.

        Args:
            h: (B, K, d_model) encoder output
            mask: (B, K) bool

        Returns:
            (B, d_model) node vector
        """
        mask_f = mask.unsqueeze(-1).float()  # (B, K, 1)
        counts = mask_f.sum(dim=1).clamp(min=1)  # (B, 1)
        pooled = (h * mask_f).sum(dim=1) / counts  # (B, d_model)
        return self.pool_norm(pooled)

    def score(self, src_vec: Tensor, dst_vec: Tensor) -> Tensor:
        """Dot-product similarity.

        Args:
            src_vec: (B, d_model)
            dst_vec: (B, d_model) or (B, N_neg, d_model)

        Returns:
            (B,) or (B, N_neg) scores
        """
        if dst_vec.dim() == 2:
            return (src_vec * dst_vec).sum(-1)
        else:
            # (B, N_neg, d) with src (B, 1, d) → (B, N_neg)
            return (src_vec.unsqueeze(1) * dst_vec).sum(-1)


def block_wise_mask(
    K: int,
    mask_ratio: float = 0.15,
    block_size: int = 4,
    device: torch.device = torch.device("cpu"),
) -> Tensor:
    """Generate block-wise mask for MTM.

    Masks contiguous blocks of tokens (not random individual tokens).
    Block-wise masking forces the model to reason over longer temporal
    spans (TGPM ICML 2026: information-theoretic necessity).

    Args:
        K: sequence length
        mask_ratio: fraction of positions to mask (approximate)
        block_size: size of each masked block
        device: target device

    Returns:
        (K,) bool mask, True = masked position
    """
    n_blocks = max(1, int(K * mask_ratio / block_size))
    # Random block start positions
    max_start = K - block_size
    if max_start <= 0:
        return torch.zeros(K, dtype=torch.bool, device=device)
    starts = torch.randint(0, max_start + 1, (n_blocks,), device=device)
    mask = torch.zeros(K, dtype=torch.bool, device=device)
    for s in starts:
        mask[s:s + block_size] = True
    return mask
